language: android
android:
  components:  
    - build-tools-25.0.2
    - android-25
    - platform-tools
    - tools
    
    # Additional components
    - extra-google-google_play_services
    - extra-google-m2repository
    - extra-android-m2repository
    - addon-google_apis-google-19
    

licenses:
- '.*'
    
jdk:
- oraclejdk8
    
before_install:
- chmod +x gradlew